<a href="https://colab.research.google.com/github/Sahilmandalwar/campusx_machine_learning_code/blob/main/ML_015_RidgeRegressionGradientDescent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes

In [46]:
from sklearn.metrics import r2_score

In [6]:
df = load_diabetes()

In [7]:
X = df.data
y = df.target

In [8]:
X.shape

(442, 10)

In [9]:
y.shape

(442,)

In [81]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [110]:
from sklearn.linear_model import SGDRegressor
sgdReg = SGDRegressor(penalty='l2',max_iter=500,eta0 = 0.005,learning_rate='constant',alpha=0.001)

In [111]:
from sklearn.linear_model import Ridge
reg = Ridge(alpha=0.001,max_iter=500,solver='sparse_cg')

In [112]:
sgdReg.fit(X_train,y_train)

SGDRegressor(alpha=0.001, eta0=0.005, learning_rate='constant', max_iter=500)

In [113]:
r2_score(y_test,sgdReg.predict(X_test))

0.43773971901662034

In [114]:
sgdReg.coef_

array([  53.7273163 ,  -79.74966877,  326.63105604,  226.04495956,
          3.81371704,  -29.12213458, -165.85351266,  137.6943893 ,
        259.18000407,  136.33873063])

In [115]:
sgdReg.intercept_

array([151.56324357])

In [116]:
class RidgeRegressionGradientDescent:
  def __init__(self,alpha,epochs=500,lr=0.005):
    self.alpha = alpha
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None
    self.lr = lr

  def fit(self,X,y):
    df_shape = X.shape
    rows = df_shape[0]
    columns = df_shape[1]
    X = np.insert(X,0,1,axis=1)
    self.coef_ = np.ones(columns)
    self.intercept_ = 0
    theta = np.insert(self.coef_, 0,self.intercept_)
    for epoch in range(self.epochs):
       theta_deri = np.dot(X.T,X).dot(theta) - np.dot(X.T,y) + self.alpha * theta
       theta = theta - self.lr * theta_deri

    self.intercept_ = theta[0]
    self.coef_ = theta[1:]

  def predict(self,X):
    return np.dot(X,self.coef_) + self.intercept_

In [117]:
clf = RidgeRegressionGradientDescent(0.001)

In [118]:
clf.fit(X_train,y_train)

In [119]:
clf.predict(X_test)

array([143.69338904, 176.02130166, 142.84729399, 288.0181049 ,
       126.35218971, 100.24021258, 250.70788263, 192.47540966,
        89.82878815, 116.73389491,  96.99633841, 153.23778105,
        66.06806921, 209.5063321 , 107.02396584, 135.79266047,
       223.24447046, 245.97848071, 192.25558403, 212.94885094,
       198.66455325,  90.31599264,  77.40086248, 188.5196274 ,
       153.01656958, 164.79738365, 187.16242071, 176.167388  ,
        52.57817634, 118.83004364, 179.19108993,  94.92258308,
       134.0393604 , 182.2238792 , 173.24292466, 189.26220267,
       128.11773642, 125.37779544, 154.54031268,  62.12372847,
        83.12322021, 113.34612812, 158.26829149, 155.26978594,
       173.20599775,  66.76749107,  83.14661936, 105.88540782,
        62.5668815 , 153.66491869, 151.06229492,  66.19806759,
       117.9906832 , 110.21277189, 170.49409624, 153.21575881,
        99.96060588, 201.8457667 , 114.87400786,  69.34778078,
       183.13220861, 194.11193221, 141.07469708, 113.30

In [120]:
clf.coef_

array([  43.37183861, -192.03766574,  496.43542567,  319.37407   ,
        -64.42788084, -113.194338  , -213.9073644 ,  144.86136322,
        367.67948022,  119.56857869])

In [121]:
clf.intercept_

np.float64(151.4045475591972)

In [122]:
r2_score(y_test,clf.predict(X_test))

0.4592249376936409