<a href="https://colab.research.google.com/github/Sahilmandalwar/campusx_machine_learning_code/blob/main/ML_014_RidgeRegressionFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [4]:
from sklearn.datasets import make_regression

In [22]:
X,y = make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=10,random_state=42)

In [25]:
X.shape

(100, 1)

In [38]:
X

array([[ 0.93128012],
       [ 0.08704707],
       [-1.05771093],
       [ 0.31424733],
       [-0.47917424],
       [ 0.64768854],
       [-0.46341769],
       [ 0.54256004],
       [ 0.61167629],
       [ 1.0035329 ],
       [ 0.8219025 ],
       [ 1.53803657],
       [ 0.73846658],
       [-0.21967189],
       [-0.8084936 ],
       [ 0.09176078],
       [-1.95967012],
       [ 0.51326743],
       [ 1.03099952],
       [-2.6197451 ],
       [ 0.49671415],
       [ 0.09707755],
       [-0.46572975],
       [ 0.91540212],
       [ 1.56464366],
       [ 1.46564877],
       [-0.60063869],
       [-0.03582604],
       [-0.60170661],
       [-1.19620662],
       [ 0.35711257],
       [ 0.37569802],
       [ 0.26105527],
       [-0.5297602 ],
       [-0.90802408],
       [ 0.19686124],
       [-0.29900735],
       [ 0.36163603],
       [ 0.82254491],
       [-0.29169375],
       [ 0.36139561],
       [-0.676922  ],
       [ 1.52302986],
       [-0.51827022],
       [-0.23415337],
       [-0

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [83]:
class RidgeRegression:
  def __init__(self,alpha):
    self.coef_ = None
    self.intercept_ = None
    self.alpha = alpha

  def fit(self,X,y):
    x_mean = X.mean()
    y_mean = y.mean()
    num = 0
    deno = 0
    for i in range(X.shape[0]):
      num += (X[i] - x_mean)*(y[i] - y_mean)
      deno += (X[i] - x_mean)**2
    deno += self.alpha
    self.coef_ = num / deno
    self.intercept_ = y_mean - x_mean * self.coef_

  def predict(self,X):
    return self.coef_* X + self.intercept_

In [84]:
r = Ridge(alpha = 0.001)

In [85]:
r.fit(X_train,y_train)


Ridge(alpha=0.001)

In [86]:
r2_score(y_test,r.predict(X_test))

0.9374144151195403

In [94]:
r.coef_,r.intercept_

(array([44.24350589]), np.float64(0.09913521014253313))

In [88]:
rr = RidgeRegression(0.001)
rr.fit(X_train,y_train)

In [93]:
rr.coef_, rr.intercept_

(array([44.24350589]), array([0.09913521]))

In [92]:
r2_score(y_test,rr.predict(X_test))

0.9374144151195403

Generalized Ridge Regularisation

In [95]:
from sklearn.datasets import load_diabetes

In [96]:
df = load_diabetes()

In [97]:
X = df['data']
y = df['target']

In [98]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [125]:
class MultipleRidgeRegression:
  def __init__(self,alpha):
    self.alpha = alpha
    self.coef_ = None
    self.intercept_ = None

  def fit(self,X,y):
    X = np.insert(X,0,1,axis=1)
    I = np.eye(X.shape[1])
    I[0][0] = 0
    w = np.linalg.inv(np.linalg.matmul(X.T, X) + self.alpha*I).dot(X.T).dot(y)
    self.intercept_ = w[0]
    self.coef_ = w[1:]

  def predict(self,X):
    return np.dot(X,self.coef_) + self.intercept_

The reason of using [0][0]=0 is that because in our metrix W the first term is basically intercept not slope and we have to multiply Lambda with only slopes.
Thats why first term became zero and lambda is multiplied with only slopes.


In [126]:
mr = MultipleRidgeRegression(0.01)

In [127]:
mr.fit(X_train,y_train)

In [128]:
mr.intercept_

np.float64(151.33659663172543)

In [129]:
mr.predict(X_test)

array([140.48932729, 180.39358466, 138.26095011, 292.70472351,
       122.54953663,  93.61127853, 256.94944065, 185.46640503,
        86.4960167 , 110.59467587,  95.04571587, 164.19550268,
        60.59798796, 205.82695673,  99.72760443, 131.91526636,
       220.91412088, 247.87634694, 195.84576355, 215.78308828,
       206.82609175,  89.01546302,  72.05374047, 188.47495433,
       155.71143723, 161.25320029, 189.08097216, 178.04173865,
        49.65268248, 110.50254797, 178.39994134,  90.08024148,
       132.14592247, 181.98946205, 173.37370782, 190.81087767,
       123.38010922, 118.90948131, 146.69459204,  60.67799313,
        74.18510938, 108.16651262, 162.96843997, 151.55290246,
       173.76202246,  64.5447612 ,  76.57353392, 109.83957197,
        56.57149752, 163.18082268, 155.2330795 ,  64.94611225,
       110.68142707, 108.69309211, 172.0029122 , 157.94954707,
        94.8588743 , 208.43411608, 118.81317959,  72.11719648,
       185.80485787, 203.47916991, 141.32147862, 105.78

In [130]:
r2_score(y_test,mr.predict(X_test))

0.4559819504579109

Actual code class

In [131]:
ridge = Ridge(alpha=0.01,solver='cholesky')

In [132]:
ridge.fit(X_train,y_train)

Ridge(alpha=0.01, solver='cholesky')

In [133]:
r2_score(y_test,ridge.predict(X_test))

0.4559819504579109