<a href="https://colab.research.google.com/github/Sahilmandalwar/campusx_machine_learning_code/blob/main/ML_031_BaggingClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_samples=10000,n_features=10,n_informative=3)

In [4]:
X

array([[-1.61880839, -1.29838301,  0.38579476, ..., -1.03127423,
        -1.41585301,  0.19277844],
       [ 1.66306853, -0.51689247, -0.60772482, ...,  2.16128681,
        -1.55462274,  0.87101201],
       [ 1.24364564, -2.36426332,  2.51518794, ..., -0.04680697,
         0.13461624,  0.65748057],
       ...,
       [-0.92697946, -0.09087636, -1.08713809, ..., -0.30414232,
        -0.9079296 ,  0.01352994],
       [-0.29540854,  0.53905484, -1.71281293, ..., -1.37248237,
         0.40680992, -1.41536408],
       [ 0.56773694,  0.50274164, -1.71845875, ...,  0.32721827,
         0.08735678,  0.39554788]])

In [5]:
y

array([0, 1, 1, ..., 1, 1, 1])

In [6]:
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [7]:
from sklearn.svm import SVC

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf = DecisionTreeClassifier(criterion='gini',max_depth=20)

In [11]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=20)

In [12]:
print("Accuracy Score: ", accuracy_score(y_test,clf.predict(X_test)))

Accuracy Score:  0.88


Bagging : through decision tree

In [13]:
bag = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=500,max_samples=0.25,bootstrap=True)

In [14]:
bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.25,
                  n_estimators=500)

In [15]:
print("Accuracy_score : ", accuracy_score(y_test,bag.predict(X_test)))

Accuracy_score :  0.924


Pasting

In [16]:
bag1 = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=500,max_samples=0.25,bootstrap=False)
bag1.fit(X_train,y_train)
print("Accuracy_score : ", accuracy_score(y_test,bag1.predict(X_test)))

Accuracy_score :  0.922


In [17]:
bag1.estimators_samples_

[array([ 214, 1780, 7962, ..., 7269, 7154, 2231]),
 array([1406, 5985, 2940, ..., 1547, 3257, 1739]),
 array([2387,  982, 4991, ..., 1250, 6536, 7980]),
 array([ 761, 6835, 7391, ..., 3790, 4731,  246]),
 array([2465, 6521, 4266, ..., 4019, 2893, 6709]),
 array([6724, 2467,  426, ..., 5139, 4613, 1537]),
 array([3308, 5287, 7069, ..., 5152,  289, 1201]),
 array([5080, 6908,  495, ..., 1276, 3556,  632]),
 array([2652, 3775, 2574, ...,  355, 7785, 4639]),
 array([3283, 2442, 3877, ..., 4236, 5603, 4978]),
 array([6281, 2201, 5883, ..., 6811, 2817, 3516]),
 array([7403, 6208, 4919, ..., 7676, 5911, 1035]),
 array([1634,   52, 3670, ..., 5858, 2123, 3508]),
 array([3777, 5429, 3260, ..., 6811, 3116, 4793]),
 array([4788,  163,  416, ..., 5978, 1395, 3462]),
 array([ 569, 2616, 3014, ..., 6292,  839, 7502]),
 array([3024, 5804, 3101, ..., 2220, 3044, 7958]),
 array([6901, 1051, 4546, ..., 3122, 2632, 4176]),
 array([  97, 7552, 5542, ..., 7792,  937, 5239]),
 array([7560, 5316, 3286, ..., 

In [18]:
bag1.estimators_features_

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),


Random Subspaces

In [19]:
bag2 = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=500,max_samples=1,max_features=0.5,bootstrap=True)
bag2.fit(X_train,y_train)
print("Accuracy_score : ", accuracy_score(y_test,bag2.predict(X_test)))

Accuracy_score :  0.481


Random Patches

In [20]:
bag3 = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=500,max_samples=0.38,max_features=0.7,bootstrap=True)
bag3.fit(X_train,y_train)
print("Accuracy_score : ", accuracy_score(y_test,bag3.predict(X_test)))

Accuracy_score :  0.9255


OOB score

In [21]:
bag3 = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=500,max_samples=0.38,max_features=0.7,bootstrap=True,oob_score=True)
bag3.fit(X_train,y_train)
print("Accuracy_score : ", accuracy_score(y_test,bag3.predict(X_test)))

Accuracy_score :  0.924


In [22]:
bag3.oob_score_

0.93075

Through Support Vector Classifier

In [23]:
bag5 = BaggingClassifier(estimator=SVC(),n_estimators=50,max_samples=0.32,bootstrap=False)
bag5.fit(X_train,y_train)
print("Accuracy Score :", accuracy_score(y_test,bag5.predict(X_test)))

Accuracy Score : 0.886


Applying GridSearchCV

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
param_grid = {
    "estimator": [DecisionTreeClassifier(),SVC(),KNeighborsClassifier()],
    "max_samples" : [0.25,0.3,0.35,0.4,0.45,0.5,0.55],
    "max_features" : [0.5,0.6,0.7,0.8],
    "bootstrap" : [True,False],
    "n_estimators" : [200,250,300,350,400,450,500,550,600]

}

In [35]:
gscv = RandomizedSearchCV(BaggingClassifier(),param_distributions=param_grid,cv=5,n_iter=10,n_jobs=-1)

In [36]:
gscv.fit(X_train,y_train)

KeyboardInterrupt: 